#:schema node_modules/wrangler/config-schema.json
name = "elec"
main = "workers/index.ts"
compatibility_date = "2025-11-17"
upload_source_maps = true
workers_dev = false

[observability]
enabled = true
traces.enabled = true

[assets]
directory = "dist"

[[d1_databases]]
binding = "DB"
database_name = "elec"
database_id = "53d81a00-e326-4bac-8940-8b9020db85d9"

[triggers]
crons = ["0 */3 * * *"]
